swagger: '2.0'
info:
  version: 1.0.0
  title: Team 190 API
  description: New website API
  
# tags are used for organizing operations
tags:
- name: uber-mentors
  description: Secure admin-only calls.
- name: users
  description: Normal functions.

paths: 
  /hello:
    post:
      tags:
        - users
      summary: Posting hello world
      description: User requests a hello.
      operationId: hello
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: HelloRequest
        description: User's name.
        schema:
          $ref: '#/definitions/Hello'
      responses:
        200:
          description: Hello Reply
          schema:
            type: object
            items:
              $ref: '#/definitions/Hello'
        400:
          description: No reply for you.
          
        
  
definitions:

  Hello:
    type: object
    required:
    - name
    properties:
      name:
        type: string
      

#Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
schemes:
 - https
basePath: /Team190/Website/1.0.0