name: CI

on: [push, pull_request]

jobs:
    build:
        name: Build front-end
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: '14'
            - name: Install packages
              run: yarn install
              working-directory: ./frontend
            - name: Build front-end
              run: yarn build
              working-directory: ./frontend
    
    deploy:
        name: Deploy to Lambda
        needs: build
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: '14'
            - name: Install Serverless
              run: npm i -g serverless@2.1.0
            - name: Deploy to Lambda
              run: serverless deploy
              working-directory: ./lambda
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              if: github.event_name == 'push' && github.ref == 'refs/heads/master'
              