name: CI

on: [push, pull_request]

jobs:
    build:
        name: Build front-end
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: '14'
            - name: Install packages
              run: yarn install
              working-directory: ./frontend
            - name: Build front-end
              run: yarn build
              working-directory: ./frontend
            - name: Push to S3
              uses: ItsKarma/aws-cli@v1.70.0
              with:
                args: aws s3 cp ./build/ s3://190website/ --recursive
              working-directory: ./frontend
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_DEFAULT_REGION: "us-east-1"
    
    deploy:
        name: Deploy to Lambda
        needs: build
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: '14'
            - name: Install Serverless plugins
              run: yarn install
              working-directory: ./lambda
            - name: Deploy to Lambda
              run: yarn deploy
              working-directory: ./lambda
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              if: github.event_name == 'push' && github.ref == 'refs/heads/master'
              